import { useState } from 'react';
import { toast } from 'sonner';
import { CheckCircle2, Copy } from 'lucide-react';
import { createClient } from '@/services/clients';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';

/**
 * "Añadir cliente" modal — email + display name. On success it shows the
 * one-time temporary password (generated by the create-client Edge Function)
 * that the coach shares with the client; it cannot be retrieved again. The
 * client signs in with it and changes it in the app's Ajustes.
 */
export function AddClientDialog({
  open,
  onOpenChange,
  onCreated,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onCreated: () => void;
}) {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const [tempPassword, setTempPassword] = useState<string | null>(null);

  const reset = () => {
    setName('');
    setEmail('');
    setError('');
    setTempPassword(null);
    setSaving(false);
  };

  const handleOpenChange = (o: boolean) => {
    onOpenChange(o);
    if (!o) reset();
  };

  const submit = async () => {
    const n = name.trim();
    const e = email.trim();
    if (!n) return setError('Escribe el nombre del cliente.');
    if (!e.includes('@') || !e.includes('.')) return setError('Escribe un correo válido.');
    setSaving(true);
    try {
      const { tempPassword: pwd } = await createClient({ display_name: n, email: e });
      setTempPassword(pwd);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'No se pudo crear el cliente.');
    } finally {
      setSaving(false);
    }
  };

  const copyPassword = async () => {
    if (!tempPassword) return;
    try {
      await navigator.clipboard.writeText(tempPassword);
      toast.success('Contraseña copiada');
    } catch {
      toast.error('No se pudo copiar — selecciónala manualmente');
    }
  };

  const done = () => {
    handleOpenChange(false);
    onCreated();
    toast.success('Cliente añadido a la lista');
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent>
        {tempPassword === null ? (
          <>
            <DialogHeader>
              <DialogTitle>Añadir cliente</DialogTitle>
              <DialogDescription>
                Se crea la cuenta con una contraseña temporal que compartes con el cliente.
              </DialogDescription>
            </DialogHeader>
            <form
              className="flex flex-col gap-3.5"
              onSubmit={(e) => {
                e.preventDefault();
                void submit();
              }}
            >
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="add-name">Nombre</Label>
                <Input
                  id="add-name"
                  placeholder="Ej. Juan Pérez"
                  value={name}
                  onChange={(e) => {
                    setName(e.target.value);
                    setError('');
                  }}
                  autoFocus
                />
              </div>
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="add-email">Correo electrónico</Label>
                <Input
                  id="add-email"
                  type="email"
                  placeholder="cliente@correo.com"
                  value={email}
                  onChange={(e) => {
                    setEmail(e.target.value);
                    setError('');
                  }}
                />
              </div>
              {error && <p className="text-[12.5px] text-primary">{error}</p>}
              <DialogFooter className="mt-2">
                <Button type="button" variant="outline" onClick={() => handleOpenChange(false)}>
                  Cancelar
                </Button>
                <Button type="submit" disabled={saving}>
                  {saving ? 'Creando…' : 'Crear cliente'}
                </Button>
              </DialogFooter>
            </form>
          </>
        ) : (
          <div className="flex flex-col items-center gap-3 px-1.5 py-3.5 text-center">
            <span className="flex h-14 w-14 items-center justify-center rounded-full bg-success/15 text-success">
              <CheckCircle2 className="h-6 w-6" strokeWidth={2} />
            </span>
            <DialogTitle>Cliente creado</DialogTitle>
            <DialogDescription className="max-w-[320px]">
              Comparte esta contraseña temporal con {name || 'el cliente'} (WhatsApp). Podrá
              cambiarla en la app en <span className="font-semibold">Ajustes</span>.
            </DialogDescription>
            <div className="flex w-full max-w-[300px] items-center gap-2">
              <code className="flex-1 select-all rounded-lg border border-border bg-muted px-3 py-2.5 font-mono text-[15px] font-semibold tracking-wide">
                {tempPassword}
              </code>
              <Button variant="outline" size="sm" onClick={() => void copyPassword()} aria-label="Copiar contraseña">
                <Copy className="h-3.5 w-3.5" strokeWidth={2} />
              </Button>
            </div>
            <p className="max-w-[300px] text-[11.5px] text-faint">
              Se muestra una sola vez — cópiala antes de cerrar.
            </p>
            <Button className="mt-1 px-6" onClick={done}>
              Listo
            </Button>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
